# Generated by Django 4.1.5 on 2023-01-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('last_seen_date', models.DateTimeField(verbose_name='Last time seen')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('closest_distance_in_meters', models.CharField(max_length=100, verbose_name='Closest distance')),
            ],
        ),
    ]
